### PR TITLE
updating httparty version

### PR DESCRIPTION
**Pull request by spodlecki**
This PR is to update HTTParty gem as other gems in the wild tend to require later versions making this gem incompatible. (HTTParty 0.10.x was released in 2013)

### CODE REVIEW

**Comment by blaix** [comment]
Sorry to nitpick, but is there a reason other than "there's a new version available", and if so, can you rewrite the commit message to include the reason?

**Comment by spodlecki** [comment]
Sorry, clicked the button and didn't get back to this PR. It is simply to keep the gems up to date. I have a few gems that use httparty and require `>= 0.13.0`

**Comment by blaix** [comment]
sounds good to me, thanks

**Comment by blaix** [comment]
released v0.1.1

**Pull request merged**
